//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// DataSearch.rc에서 사용되고 있습니다.
//
#define IDD_DIALOG_DATA_SEARCH          1000
#define IDC_STATIC_LOT_ID               1000
#define IDC_DATETIMEPICKER_3            1001
#define IDC_DATETIMEPICKER_END_DAY      1001
#define IDC_STATIC_RECIPE               1001
#define IDC_RADIO_1                     1002
#define IDC_RADIO_RAW                   1002
#define IDC_STATIC_LOT_FINAL_METER      1002
#define IDC_RADIO_2                     1003
#define IDC_RADIO_LOT                   1003
#define IDC_STATIC_LOT_DEFECT_NAME      1003
#define IDC_DATETIMEPICKER_2            1004
#define IDD_DIALOG_SEARCH_DEFECTRAW     1004
#define IDC_DATETIMEPICKER_START_TIME   1004
#define IDC_STATIC_TOTAL_DEFECT         1004
#define IDC_LIST_1                      1005
#define IDC_LIST_CSV_FIND_FILE          1005
#define IDC_EDIT_RECIPE                 1005
#define IDC_LIST_2                      1006
#define IDC_LIST_CSV_INFO               1006
#define IDD_DIALOG_SEARCH_LOT           1006
#define IDC_EDIT_TOTAL_DEFECT_NUM       1006
#define IDC_EDIT_SEARCH_BLANK           1007
#define IDC_BUTTON_FIND                 1008
#define IDD_DIALOG_DEFECTTIMETABLE      1008
#define IDC_DATETIMEPICKER_7            1009
#define IDC_DATETIMEPICKER_START_DAY    1009
#define IDC_EDIT_MODE                   1010
#define IDC_STATIC_STATUS               1010
#define IDC_EDIT_LOT_FINAL_METER        1011
#define IDC_STATIC_AVG_GV               1011
#define IDC_EDIT_PATTERN_NUM            1012
#define IDC_STATIC_MIN_GV               1012
#define IDC_EDIT_LAIN_NUM               1013
#define IDC_STATIC_MAX_GV               1013
#define IDC_COMBO_DEFECT_NAME           1014
#define IDC_STATIC_BRIGHT_AVG           1014
#define IDC_DATETIMEPICKER_4            1015
#define IDC_DATETIMEPICKER_END_TIME     1015
#define IDC_EDIT_LOT_ID                 1015
#define IDC_EDIT_DIMENSION_TYPE         1015
#define IDC_DATETIMEPICKER_5            1016
#define IDC_DATETIMEPICKER_LOT_START_TIME 1016
#define IDC_STATIC_DARK_GV              1016
#define IDC_DATETIMEPICKER_6            1017
#define IDC_DATETIMEPICKER_LOT_END_TIME 1017
#define IDC_STATIC_SIZE_X               1017
#define IDC_STATIC_START_TIME           1018
#define IDC_STATIC_LOT_START_TIME       1018
#define IDC_STATIC_SIZE_Y               1018
#define IDC_STATIC_END_TIME             1019
#define IDC_STATIC_LOT_END_TIME         1019
#define IDC_STATIC_RATIO_AREA           1019
#define IDC_STATIC_ELECTRODE_TYPE       1020
#define IDC_STATIC_RATIO_YX             1020
#define IDC_EDIT_TOTAL_LAIN_NUM2        1020
#define IDC_STATIC_MODE                 1021
#define IDC_STATIC_RATIO_XY             1021
#define IDC_EDIT_TOTAL_PPK              1021
#define IDC_STATIC_CAM_INDEX            1022
#define IDC_STATIC_COMPACT              1022
#define IDC_STATIC_PATTERN_NUM          1023
#define IDC_STATIC_RATIO_WHITE          1023
#define IDC_STATIC_RAW_RECIPE           1023
#define IDC_STATIC_LAIN_NUM             1024
#define IDC_STATIC_PATTERN_NUMBER       1024
#define IDC_STATIC_RATIO_DARK           1024
#define IDC_STATIC_DEFECT_NAME          1025
#define IDC_STATIC_LAIN_NUMBER          1025
#define IDC_STATIC_EDGE_ENERGY          1025
#define IDC_STATIC_IMAGE_VIEW           1026
#define IDC_STATIC_IMAGE_VIEW_BRIGHT    1026
#define IDC_STATIC_DEFECT_NAME2         1026
#define IDC_STATIC_LAIN_NUMBER2         1026
#define IDC_COMBO_ELECTRODE_TYPE        1027
#define IDC_STATIC_MASS_CENTER          1027
#define IDC_STATIC_LOT_TOTAL_PPK        1027
#define IDC_COMBO_CAM_INDEX             1028
#define IDC_STATIC_LOTID                1028
#define IDC_STATIC_ADD_SEARCH           1029
#define IDC_STATIC_CELLID               1029
#define IDC_STATIC_DEFECT_INFO          1030
#define IDC_STATIC_TOTAL_PPK            1030
#define IDC_STATIC_RAW_METER            1030
#define IDC_STATIC_DIMENSION_TYPE       1030
#define IDC_STATIC_DETAIL_DATASEARCH    1031
#define IDC_STATIC_RAW_WIDTH_LENGTH     1031
#define IDC_STATIC_IMAGE_VIEW_DARK      1032
#define IDC_STATIC_RAW_AREA             1032
#define IDC_STATIC_TIME                 1033
#define IDC_STATIC_RAW_X_SIZE           1033
#define IDC_STATIC_DEFECT_TYPE          1034
#define IDC_STATIC_RAW_Y_SIZE           1034
#define IDC_STATIC_TOP_BACK             1035
#define IDC_STATIC_RAW_DEFECT_X         1035
#define IDC_STATIC_DEFECT_X             1036
#define IDC_STATIC_RAW_DEFECT_Y         1036
#define IDC_STATIC_DEFECT_Y             1037
#define IDC_STATIC_RAW_MAX_GV           1037
#define IDC_STATIC_JUDGE                1038
#define IDC_STATIC_RAW_MIN_GV           1038
#define IDC_LIST_SELECT_INFO            1039
#define IDC_STATIC_RAW_AVG_GV           1039
#define IDC_BUTTON_EXPORT               1040
#define IDC_STATIC_RAW_DEFECT_AREA_GV   1040
#define IDC_BUTTON_INPUT                1041
#define IDC_BUTTON_OUTPUT               1042
#define IDC_CHECK_CROP                  1043
#define IDC_BUTTON_RESET                1044
#define IDC_BUTTON_EXCELCLEAR           1045
#define IDC_EDIT_RAW_RECIPE             1045
#define IDC_EDIT_RAW_METER              1046
#define IDC_RADIO_LOT2                  1046
#define IDC_RADIO_NONE                  1046
#define IDC_EDIT_RAW_WIDTH_LENGTH       1047
#define IDC_STATIC_LOT_END_TIME2        1047
#define IDC_BUTTON_DEFECTCSVEXPORT      1047
#define IDC_EDIT_RAW_AREA               1048
#define IDC_EDIT_RAW_X_SIZE             1049
#define IDC_EDIT_RAW_Y_SIZE             1050
#define IDC_EDIT_RAW_DEFECT_X           1051
#define IDC_EDIT_RAW_DEFECT_Y           1052
#define IDC_EDIT_RAW_MAX_GV             1053
#define IDC_EDIT_RAW_MIN_GV             1054
#define IDC_EDIT_RAW_AVG_GV             1055
#define IDC_EDIT_RAW_DEFECT_AREA_GV     1056
#define IDC_DATETIMEPICKER_RAW_START_TIME 1057
#define IDC_DATETIMEPICKER_RAW_END_TIME 1058
#define IDC_COMBO_RAW_DEFECT_NAME       1059
#define IDC_EDIT_RAW_LAIN_NUM           1060
#define IDC_LIST_DEFECTTIMETABLE        1061
#define IDC_CHECK1                      1062
#define IDC_CHECK_DEFECTPOSIMAGEADD     1062

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1010
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1063
#define _APS_NEXT_SYMED_VALUE           1000
#endif
#endif
