#include "stdafx.h"
#include "basedef.h"
#include "CISIDefectProperty.h"
#include "CISIDefectResult.h"

using namespace classification;


CISIDefectProperty::CISIDefectProperty()
	: nInspectImage(_T("nInspectImage"), enInspectionImageType::IIT_None)
	, nDefectBrightness(_T("nDefectBrightness"), enDefectBrightness::DFB_NONE)	
	, nCategory(_T("nCategory"), enCategory::CTG_NONE)			
	, nInspectionArea(_T("nInspectionArea"), enInspectionArea::IA_NONE)
	, rtRect_pixel(_T("rtRect_pixel"), IPVM::Rect())
	, SIZE_X_mm(_T("SIZE_X_mm"), 0)
	, SIZE_Y_mm(_T("SIZE_Y_mm"), 0)
	, AREA(_T("AREA"), 0)
	, AREA_Ratio(_T("AREA_Ratio"), 0)
    , SMALL_INSP(_T("SMALL_INSP"), 0)
    , SMALL_INSP_LEVEL(_T("SMALL_INSP_LEVEL"), 0)
    , PARENT(_T("PARENT"), 0)
	, WIDTH_mm(_T("WIDTH_mm"), 0)
	, LENGTH_mm(_T("LENGTH_mm"), 0)
	, RATIO_WL(_T("RATIO_WL"), 0)
	, RATIO_LW(_T("RATIO_LW"), 0)
	, RATIO_YX(_T("RATIO_YX"), 0)
	, RATIO_XY(_T("RATIO_XY"), 0)
	, ANGLE(_T("ANGLE"), 0)
	, STD(_T("STD"), 0)
	, COMPACT(_T("COMPACT"), 0)
	, AVG_GV(_T("AVG_GV"), 0)
	, MIN_GV(_T("MIN_GV"), 0)
	, MAX_GV(_T("MAX_GV"), 0)
	, BRIGHT_AVG_GV(_T("BRIGHT_AVG_GV"), 0)
	, DARK_AVG_GV(_T("DARK_AVG_GV"), 0)
	, BLOB_THRESHOLD(_T("BLOB_THRESHOLD_T"), 0)
	, SECTION_THRESHOLD(_T("SECTION_THRESHOLD_T"), 0)
	, RATIO_WHITE(_T("RATIO_WHITE"),0) // [sm]
	, RATIO_DARK(_T("RATIO_DARK"), 0)
	, EDGE_ENERGY(_T("EDGE_ENERGY"), 0)
    , EDGE_ENERGY_BLACK(_T("EDGE_ENERGY_BLACK"), 0)
    , EDGE_ENERGY_WHITE(_T("EDGE_ENERGY_WHITE"), 0)
	//, RATIO_AREA(_T("RATIO_AREA"), 0)
	, MASS_CENTER_GV_GV(_T("MASS_CENTER_GV_GV"), 0)
	, HOR(_T("HOR"), 0)
	, VER(_T("VER"), 0)
	, RATIO_HV(_T("RATIO_HV"), 0)
	, RATIO_VH(_T("RATIO_VH"), 0)
    , OVER_200_GV_PIXEL_COUNT(_T("OVER_GV_PIXEL_COUNT"), 0)
    , DISTANCE_TO_EDGE_mm(_T("DISTANCE_TO_EDGE_mm"), 0)
    , DISTANCE_TO_EDGE_2_mm(_T("DISTANCE_TO_EDGE_2_mm"), 0)
    , IS_NEAR_EDGE(_T("IS_NEAR_EDGE"), 0)
    , PRIORITY(_T("PRIORITY"), 0)
    , EDGE_ENERGY_SHARPNESS(_T("EDGE_ENERGY_SHARPNESS"), 0)
    , EDGE_ENERGY_SHARPNESS_WHITE(_T("EDGE_ENERGY_SHARPNESS_WHITE"), 0)
    , EDGE_ENERGY_SHARPNESS_BLACK(_T("EDGE_ENERGY_SHARPNESS_BLACK"), 0)
    , MEDIAN_GV(_T("MEDIAN_GV"),0)
    , STDEV_GV(_T("STDEV_GV"),0)
	// 장지수 _2 변수 추가
    , AREA_2(_T("AREA_2"), 0)
    , AREA_Ratio_2(_T("AREA_Ratio_2"), 0)
    , SMALL_INSP_2(_T("SMALL_INSP_2"), 0)
    , SMALL_INSP_LEVEL_2(_T("SMALL_INSP_LEVEL_2"), 0)
    , WIDTH_mm_2(_T("WIDTH_mm_2"), 0)
    , LENGTH_mm_2(_T("LENGTH_mm_2"), 0)
    , RATIO_WL_2(_T("RATIO_WL_2"), 0)
    , RATIO_LW_2(_T("RATIO_LW_2"), 0)
    , RATIO_YX_2(_T("RATIO_YX_2"), 0)
    , RATIO_XY_2(_T("RATIO_XY_2"), 0)
    , ANGLE_2(_T("ANGLE_2"), 0)
    , STD_2(_T("STD_2"), 0)
    , COMPACT_2(_T("COMPACT_2"), 0)
    , AVG_GV_2(_T("AVG_GV_2"), 0)
    , MIN_GV_2(_T("MIN_GV_2"), 0)
    , MAX_GV_2(_T("MAX_GV_2"), 0)
    , BRIGHT_AVG_GV_2(_T("BRIGHT_AVG_GV_2"), 0)
    , DARK_AVG_GV_2(_T("DARK_AVG_GV_2"), 0)
    , RATIO_WHITE_2(_T("RATIO_WHITE_2"), 0) // [sm]
    , RATIO_DARK_2(_T("RATIO_DARK_2"), 0)
    , EDGE_ENERGY_2(_T("EDGE_ENERGY_2"), 0)
    , EDGE_ENERGY_BLACK_2(_T("EDGE_ENERGY_BLACK_2"), 0)
    , EDGE_ENERGY_WHITE_2(_T("EDGE_ENERGY_WHITE_2"), 0)
    //, RATIO_AREA(_T("RATIO_AREA"), 0)
    , MASS_CENTER_GV_GV_2(_T("MASS_CENTER_GV_GV_2"), 0)
    , HOR_2(_T("HOR_2"), 0)
    , VER_2(_T("VER_2"), 0)
    , RATIO_HV_2(_T("RATIO_HV_2"), 0)
    , RATIO_VH_2(_T("RATIO_VH_2"), 0)
    , OVER_200_GV_PIXEL_COUNT_2(_T("OVER_GV_PIXEL_COUNT_2"), 0)
    , DISTANCE_TO_EDGE_mm_2(_T("DISTANCE_TO_EDGE_mm_2"), 0)
    , DISTANCE_TO_EDGE_2_mm_2(_T("DISTANCE_TO_EDGE_2_mm_2"), 0)
    , IS_NEAR_EDGE_2(_T("IS_NEAR_EDGE_2"), 0)
    , SECTION_THRESHOLD_2(_T("SECTION_THRESHOLD_T_2"), 0)
    , EDGE_ENERGY_SHARPNESS_2(_T("EDGE_ENERGY_SHARPNESS_2"), 0)
    , EDGE_ENERGY_SHARPNESS_WHITE_2(_T("EDGE_ENERGY_SHARPNESS_WHITE_2"), 0)
    , EDGE_ENERGY_SHARPNESS_BLACK_2(_T("EDGE_ENERGY_SHARPNESS_BLACK_2"), 0)
{
	
}



//result
