#pragma once
#include "resource.h"
#include "afxwin.h"
#include "basedef.h"
#include "DebugInfo.h"
#include "InspectionSetupImage.h"
#include "ProcessingItemDef.h"
#include "Types/Image_8u_C1.h"

#include "../CompanySharedLibrary/Persistence/Database.h"
#include "../SharedModule/VisionHostShare//LoginInfo.h"
#include "../VisionModule/Base/ParaBool.h"
#include "Algorithm/EdgeDetectionDebugInfo.h"
#include "Excel/ExcelWrapClass.h"
#include "CISIDefectProperty.h"
// 장지수 Batch Inspection 을 위해 Class 추가
#include "CDlgBatchInpection.h"

class CDlgBatchInpection;

#define WM_USER_MESSAGE_BOX_YES + 2000
#define WM_UPDATE_PROFILEVIEW			(WM_USER + 102)
#define UWM_UPDATE_EDIT_INSPECTIONITEM (WM_USER + 1000)

enum
{
    //DImension Dialog Control List Start
    IDC_BTN_CRITERIA_OPTIONS = 1001,
    IDC_BTN_MEASURE_OFFSET,
    IDC_BTN_MERGE_OPTIONS,
    IDC_BTN_ISI_CRITERIA,
    IDC_BTN_ISI_DIMENSION_CRITERIA,
    IDC_BTN_SPACE,
    IDC_BTN_CELL_DESIGN,
    IDC_PARA_SWAP_MIN_AREA_BOX_XY,
	IDC_BTN_BLOB_ADD_INSP_AREA,
	IDC_BTN_BLOB_DELETE_INSP_AREA,
    IDC_BTN_UPSIDE_CONFIGURATION,
    IDC_BTN_UPSIDE_CELL_ALIGN,
    IDC_BTN_UPSIDE_UNCOATING,
    IDC_BTN_UPSIDE_TAPE,
    IDC_BTN_UPSIDE_SURFACE,
    IDC_BTN_UPSIDE_SCRAB,
    IDC_BTN_UPSIDE_TAB,
    //IDC_BTN_UPSIDE_FOLDING,
    IDC_BTN_UPSIDE_SHOULDERLINE,
    IDC_BTN_UPSIDE_ELECTRODE_TORN,
    IDC_BTN_UPSIDE_NG_MARK,
    IDC_BTN_UPSIDE_MEASURE,
    IDC_BTN_UPSIDE_CHATTERING,
    IDC_BTN_UPSIDE_BURR,
    IDC_BTN_UPSIDE_ETC,
    IDC_BTN_UPSIDE_ISI,
	IDC_BTN_UPSIDE_DEEPLEARNING,
	IDC_BTN_UPSIDE_ABNORMAL_INSPECTION,
	IDC_BTN_UPSIDE_BLOB,

    IDC_BTN_DOWNSIDE_CONFIGURATION,
    IDC_BTN_DOWNSIDE_CELL_ALIGN,
    IDC_BTN_DOWNSIDE_UNCOATING,
    IDC_BTN_DOWNSIDE_TAPE,
    IDC_BTN_DOWNSIDE_SURFACE,
    IDC_BTN_DOWNSIDE_SCRAB,
    IDC_BTN_DOWNSIDE_TAB,
    //IDC_BTN_DOWNSIDE_FOLDING,
    IDC_BTN_DOWNSIDE_SHOULDERLINE,
    IDC_BTN_DOWNSIDE_ELECTRODE_TORN,
    IDC_BTN_DOWNSIDE_NG_MARK,
    IDC_BTN_DOWNSIDE_MEASURE,
    IDC_BTN_DOWNSIDE_CHATTERING,
    IDC_BTN_DOWNSIDE_BURR,
    IDC_BTN_DOWNSIDE_ETC,
    IDC_BTN_DOWNSIDE_ISI,
	IDC_BTN_DOWNSIDE_DEEPLEARNING,
	IDC_BTN_DOWNSIDE_ABNORMAL_INSPECTION,
	IDC_BTN_DOWNSIDE_BLOB,

    IDC_PARA_CELL_DESIGN_SHOW_OVERLAY,
    IDC_PARA_CELL_DESIGN_OVERLAY_X_AXIS_MOVE,
    IDC_PARA_CELL_DESIGN_OVERLAY_Y_AXIS_MOVE,
	IDC_PARA_CELL_DESIGN_MIRROR_IMAGE,

    IDC_PARA_CONFIGURATION_THRESHOLD_VALUE,
    IDC_PARA_CONFIGURATION_THRESHOLD_TYPE,
    IDC_PARA_CONFIGURATION_SCAN_POSITION_LEFT,
    IDC_PARA_CONFIGURATION_SCAN_POSITION_RIGHT,
    IDC_PARA_CONFIGURATION_MARK_LOWER_THRESHOLD_LEFT,
    IDC_PARA_CONFIGURATION_MARK_LOWER_THRESHOLD_RIGHT,

    IDC_PARA_TILT_EDGE_AUTOMANUAL,
    IDC_PARA_TILT_EDGE_SHOWCURRENTSETTING,
    IDC_PARA_BACKGROUND_LEFT,
    IDC_PARA_BACKGROUND_RIGHT,
    IDC_PARA_BOUNDARY_SEARCH_SIZE,
    IDC_PARA_EDGE_SEARCH_DIRECTION,
    IDC_PARA_SHOW_ROI,
    IDC_PARA_V_HOME_EXISTANCE,
    IDC_PARA_V_HOME_SHAPE_INSPECTION,
    IDC_PARA_V_HOME_SHAPE_CROSSCEHCK,
    IDC_PARA_V_HOME_SHAPE_MINY,
    IDC_PARA_V_HOME_SHAPE_MAXY,
    IDC_PARA_V_HOME_MAKE_UPPER_USING_IMAGE,
    IDC_PARA_V_HOME_MAKE_UPPER_LEFT,
    IDC_PARA_V_HOME_MAKE_UPPER_LEFT_VALUE,
    IDC_PARA_V_HOME_MAKE_UPPER_RIGHT,
    IDC_PARA_V_HOME_MAKE_UPPER_RIGHT_VALUE,
    IDC_PARA_V_HOME_MAKE_UPPER_ROI_MOVE,
    IDC_PARA_V_HOME_MAKE_UPPER_COMPARE_XPOS,
    IDC_PARA_ALIGN_VHOME_THRESHOLD_IMAGE_OPTION,
    IDC_PARA_ALIGN_VHOME_THRESHOLD_LEFT,
    IDC_PARA_ALIGN_VHOME_THRESHOLD_RIGHT,
    IDC_PARA_USE_NEW_V_HOME_EDGE_DETECT,
    IDC_PARA_V_HOME_MOVE_TOGETHER,
    IDC_PARA_USE_VHOME_Y_COMPENSATE,
    IDC_PARA_USE_VHOME_HEIGHT,
    IDC_PARA_FIND_VHOME_FROM_DARK_PIXEL,
    IDC_PARA_VHOME_DETAIL_LEFT,
    IDC_PARA_VHOME_DETAIL_RIGHT,
    IDC_PARA_USE_VHOME_MISALIGN_DETAIL,
    IDC_PARA_RIGHT_VHOME_IS_ABOVE_THE_LEFT,
    IDC_PARA_VHOME_OFFSET_PIXEL,
    IDC_PARA_AVHOME_MISALIGN_DETAIL_LEFT_IMAGE_UP,
    IDC_PARA_AVHOME_MISALIGN_DETAIL_RIGHT_IMAGE_UP,
    IDC_PARA_AVHOME_MISALIGN_DETAIL_LEFT_IMAGE_DOWN,
    IDC_PARA_AVHOME_MISALIGN_DETAIL_RIGHT_IMAGE_DOWN,
    IDC_PARA_MISALIGN_DETAIL_LEFT_UP_OPTION,
    IDC_PARA_MISALIGN_DETAIL_LEFT_DOWN_OPTION,
    IDC_PARA_MISALIGN_DETAIL_RIGHT_UP_OPTION,
    IDC_PARA_MISALIGN_DETAIL_RIGHT_DOWN_OPTION,
    IDC_PARA_USE_WHITEST_ROLLER_IN_THE_BRIGHT_IMAGE,
    IDC_PARA_USE_NONECOATING_AUTODETECT,
    IDC_PARA_ALIGN_ROLLER_DARK_NOISE_THRESHOLD,
    IDC_PARA_ALIGN_GROOVE_DARK_THRESHOLD,
    IDC_PARA_ALIGN_GROOVE_DARK_THRESHOLD_NOTAB,
    IDC_PARA_ALIGN_TAB_THRESHOLD,
    IDC_PARA_ALIGN_VHOME_ROI,
    IDC_PARA_MANUAL_TAB_ROI,
    IDC_PARA_DEFECT_LINE_COUNT_MEASURE,
	IDC_PARA_DEFECT_LINE_COUNT_BLOB,
    IDC_PARA_INNER_DETAIL_SEARCH_OFFSET,
    IDC_PARA_OUTER_DETAIL_SEARCH_OFFSET,
    IDC_PARA_ROLLER_BOUNDARY_LINE_FOR_TAB,
    IDC_PARA_USE_FIND_TAB_AUTO,
    IDC_PARA_JUDGE_TAB_EDGE_TYPE,
    IDC_PARA_JUDGE_USABLE_COUNT,
    IDC_PARA_TOP_BOTTOM_EDGE_SAMPLING_COUNT,
    IDC_PARA_USE_FIRST_EDGE_AT_FIND_TAB_AUTO,
    IDC_PARA_EDGE_VALUE_FIND_TAB_AUTO,
    IDC_PARA_TAB_AUTO_HALF_FILTER_LENGTH,
    IDC_PARA_TAB_AUTO_GAUSSIAN_DEVIATION,
    IDC_PARA_TAB_AUTO_RANSAC_DISTANCE_THRESHOLD,
    IDC_PARA_TAB_AUTO_USE_PREPROCESS_WHEN_CALC_FROM_BLOB,
    IDC_PARA_TAB_AUTO_SUBTRACT_SCALE_FACTOR,
    IDC_PARA_TAB_AUTO_MULTIPLY_RATIO,
    IDC_PARA_TAB_AUTO_MULTIPLY_SCALE_FACTOR,
    IDC_PARA_TAB_AUTO_TAB_POSITION,
    IDC_PARA_USE_SEARCH_TAB_LEFT_FROM_V_HOME,
    IDC_PARA_ALIGN_CELL_BOUNDARY_BASE_LINE,
    IDC_PARA_USE_DETAIL_CELL_BOUNDARY,
    IDC_PARA_BUTTON_RIGHT_CELLBOUNDARY_EDGE_PARA,
    IDC_PARA_BUTTON_LEFT_CELLBOUNDARY_EDGE_PARA,
    IDC_PARA_BUTTON_LEFTVHOME_EDGE_PARA,
    IDC_PARA_BUTTON_TABRiGHT_EDGE_PARA,

	IDC_PARA_BUTTON_LINEDETECT_PARA_MEASURE_00,
	IDC_PARA_BUTTON_LINEDETECT_PARA_MEASURE_20 = IDC_PARA_BUTTON_LINEDETECT_PARA_MEASURE_00 + 20,

	IDC_PARA_BUTTON_LINEDETECT_PARA_BLOB_00,
	IDC_PARA_BUTTON_LINEDETECT_PARA_BLOB_20 = IDC_PARA_BUTTON_LINEDETECT_PARA_BLOB_00 + 20,

	IDC_PARA_BUTTON_COPY_MEASURE_ROI,
    IDC_PARA_BUTTON_COPY_BLOB_ROI,
    IDC_PARA_BUTTON_AUTO_FIND_EDGEDETECT_ROI,
    IDC_PARA_MEASURE_SELECT_IMAGE_TYPE, 
	IDC_PARA_ALIGN_SELECT_IMAGE_TYPE,
    IDC_PARA_ALIGN_SELECT_INSPTYPE,
	IDC_PARA_ALIGN_SELECT_IMAGE_MIRROR,
    IDC_PARA_BUTTON_MSA_ALIGN,
	
	IDC_PARA_BLOB_USE_INSPECTION_000,
    IDC_PARA_BLOB_USE_INSPECTION_399 = IDC_PARA_BLOB_USE_INSPECTION_000 + 399,
    IDC_PARA_BLOB_DELETE_INTERSECT_BLOB_000,
    IDC_PARA_BLOB_DELETE_INTERSECT_BLOB_399 = IDC_PARA_BLOB_DELETE_INTERSECT_BLOB_000 + 399,
    IDC_PARA_BLOB_THRESHOLD_000,
    IDC_PARA_BLOB_THRESHOLD_399 = IDC_PARA_BLOB_THRESHOLD_000 + 399,
	//
	IDC_PARA_BLOB_THRESHOLD2_000,
	IDC_PARA_BLOB_THRESHOLD2_399 = IDC_PARA_BLOB_THRESHOLD2_000 + 399,
	//
    IDC_PARA_BLOB_BLOB_MIN_SIZE_000,
    IDC_PARA_BLOB_BLOB_MIN_SIZE_399 = IDC_PARA_BLOB_BLOB_MIN_SIZE_000 + 399,
	//
	IDC_PARA_BLOB_MCGVSIZE_000,
	IDC_PARA_BLOB_MCGVSIZE_399 = IDC_PARA_BLOB_MCGVSIZE_000 + 399,
	IDC_PARA_BLOB_THRESHOL_HOR_DIV_000,
	IDC_PARA_BLOB_THRESHOL_HOR_DIV_399 = IDC_PARA_BLOB_THRESHOL_HOR_DIV_000 + 399,
	IDC_PARA_BLOB_THRESHOL_VER_DIV_000,
	IDC_PARA_BLOB_THRESHOL_VER_DIV_399 = IDC_PARA_BLOB_THRESHOL_VER_DIV_000 + 399,
	IDC_PARA_BLOB_BLOB_MERGE_DISTANCE_000,
	IDC_PARA_BLOB_BLOB_MERGE_DISTANCE_399 = IDC_PARA_BLOB_BLOB_MERGE_DISTANCE_000 + 399,
    IDC_PARA_BLOB_BLOB_INTERSECT_MERGE_000,
    IDC_PARA_BLOB_BLOB_INTERSECT_MERGE_399 = IDC_PARA_BLOB_BLOB_INTERSECT_MERGE_000 + 399,
	//
	IDC_PARA_BLOB_USE_EQUAL_000,
    IDC_PARA_BLOB_USE_EQUAL_399 = IDC_PARA_BLOB_USE_EQUAL_000 + 399,

	IDC_PARA_BLOB_USE_EQUAL_THRESHOLD_000,
	IDC_PARA_BLOB_USE_EQUAL_THRESHOLD_399 = IDC_PARA_BLOB_USE_EQUAL_THRESHOLD_000 + 399,
	IDC_PARA_BLOB_EQUAL_THRESHOLD_MAX_000,
	IDC_PARA_BLOB_EQUAL_THRESHOLD_MAX_399 = IDC_PARA_BLOB_EQUAL_THRESHOLD_MAX_000 + 399,
	IDC_PARA_BLOB_EQUAL_THRESHOLD_MIN_000,
	IDC_PARA_BLOB_EQUAL_THRESHOLD_MIN_399 = IDC_PARA_BLOB_EQUAL_THRESHOLD_MIN_000 + 399,
	IDC_PARA_BLOB_EQUAL_THREAD_COUNT_000,
    IDC_PARA_BLOB_EQUAL_THREAD_COUNT_399 = IDC_PARA_BLOB_EQUAL_THREAD_COUNT_000 + 399,


    IDC_PARA_BLOB_BLOB_MAX_COUNT_000,
    IDC_PARA_BLOB_BLOB_MAX_COUNT_399 = IDC_PARA_BLOB_BLOB_MAX_COUNT_000 + 399,
    IDC_PARA_BLOB_BLOB_TIMEOUT_000,
    IDC_PARA_BLOB_BLOB_TIMEOUT_399 = IDC_PARA_BLOB_BLOB_TIMEOUT_000 + 399,
    IDC_PARA_BLOB_BLOB_MIN_LENGTH_000,
    IDC_PARA_BLOB_BLOB_MIN_LENGTH_399 = IDC_PARA_BLOB_BLOB_MIN_LENGTH_000 + 399,
	IDC_PARA_BLOB_BLOB_TYPE_IMAGE_000,
	IDC_PARA_BLOB_BLOB_TYPE_IMAGE_399 = IDC_PARA_BLOB_BLOB_TYPE_IMAGE_000 + 399,
	IDC_PARA_BLOB_BLOB_TYPE_THRESHOLD_BRIGHT_000,
	IDC_PARA_BLOB_BLOB_TYPE_THRESHOLD_BRIGHT_399 = IDC_PARA_BLOB_BLOB_TYPE_THRESHOLD_BRIGHT_000 + 399,
	IDC_PARA_BLOB_BLOB_TYPE_INSPECTION_000,
	IDC_PARA_BLOB_BLOB_TYPE_INSPECTION_399 = IDC_PARA_BLOB_BLOB_TYPE_INSPECTION_000 + 399,
	
	IDC_PARA_BLOB_INSP_AREA_ROI_000,
	IDC_PARA_BLOB_INSP_AREA_ROI_399 = IDC_PARA_BLOB_INSP_AREA_ROI_000 + 399,
	IDC_PARA_BLOB_TYPE_SET_INSP_ROI_000,
	IDC_PARA_BLOB_TYPE_SET_INSP_ROI_399 = IDC_PARA_BLOB_TYPE_SET_INSP_ROI_000 + 399,
	IDC_PARA_BLOB_OFFSET_ROI_000,
	IDC_PARA_BLOB_OFFSET_ROI_399 = IDC_PARA_BLOB_OFFSET_ROI_000 + 399,
	IDC_PARA_BLOB_SIZE_WIDTH_ROI_000,
	IDC_PARA_BLOB_SIZE_WIDTH_ROI_399 = IDC_PARA_BLOB_SIZE_WIDTH_ROI_000 + 399,
	IDC_PARA_BLOB_START_POS_ROI_OFFSET_000,
	IDC_PARA_BLOB_START_POS_ROI_OFFSET_399 = IDC_PARA_BLOB_START_POS_ROI_OFFSET_000 + 399,
    IDC_PARA_BLOB_USE_MEAN_RANGE_THRESHOLD_000,
    IDC_PARA_BLOB_USE_MEAN_RANGE_THRESHOLD_399 = IDC_PARA_BLOB_USE_MEAN_RANGE_THRESHOLD_000 +399,
	IDC_PARA_MEASURE_ITEM_COUNT,
	IDC_PARA_MEASURE_LINE_CAL,
	IDC_PARA_MEASURE_ITEM_TYPE,
	IDC_PARA_MEASURE_ITEM_TYPE_49 = IDC_PARA_MEASURE_ITEM_TYPE + 49,
	IDC_PARA_MEASURE_ITEM_START,
	IDC_PARA_MEASURE_ITEM_START_49 = IDC_PARA_MEASURE_ITEM_START + 49,
	IDC_PARA_MEASURE_ITEM_END,
	IDC_PARA_MEASURE_ITEM_END_49 = IDC_PARA_MEASURE_ITEM_END + 49,
	IDC_PARA_MEASURE_ITEM_STANDARD,
	IDC_PARA_MEASURE_ITEM_STANDARD_49 = IDC_PARA_MEASURE_ITEM_STANDARD + 49,
	IDC_PARA_MEASURE_ITEM_OFFSETUSL,
	IDC_PARA_MEASURE_ITEM_OFFSETUSL_49 = IDC_PARA_MEASURE_ITEM_OFFSETUSL + 49,
	IDC_PARA_MEASURE_ITEM_OFFSETLSL,
	IDC_PARA_MEASURE_ITEM_OFFSETLSL_49 = IDC_PARA_MEASURE_ITEM_OFFSETLSL + 49,
    IDC_PARA_MEASURE_ITEM_OFFSETUCL,
    IDC_PARA_MEASURE_ITEM_OFFSETUCL_49 = IDC_PARA_MEASURE_ITEM_OFFSETUCL + 49,
    IDC_PARA_MEASURE_ITEM_OFFSETLCL,
    IDC_PARA_MEASURE_ITEM_OFFSETLCL_49 = IDC_PARA_MEASURE_ITEM_OFFSETLCL + 49,

	IDC_PARA_BLOBCRITERIA_COUNT,
	IDC_PARA_BLOBCRITERIA_SELECT_DEFECTNAME,
	IDC_PARA_BLOBCRITERIA_SELECT_DEFECTNAME_49 = IDC_PARA_BLOBCRITERIA_SELECT_DEFECTNAME + 49,
	IDC_PARA_BLOBCRITERIA_SELECT_ROI,
	IDC_PARA_BLOBCRITERIA_SELECT_ROI_49 = IDC_PARA_BLOBCRITERIA_SELECT_ROI + 49,
	IDC_PARA_BUTTON_BLOB_CRITERIA_SETTING,
	IDC_PARA_BUTTON_BLOB_CRITERIA_SETTING_49 = IDC_PARA_BUTTON_BLOB_CRITERIA_SETTING + 49,

	IDC_PARA_ABNORMAL_OFFSET_ROI,
	IDC_PARA_ABNORMAL_GV,
    IDC_PARA_ABNORMAL_GV_2,
	IDC_PARA_ABNORMAL_USE_INSPECTION,
    IDC_PARA_ABNORMAL_SET_USER_ROI,

	IDC_PARA_CHATTERING_USE_INSPECTION,
    IDC_PARA_CHATTERING_SELECT_DARK_IMAGE,
	IDC_PARA_CHATTERING_DIV_COUNT,
    IDC_PARA_CHATTERING_STANDARD,
    IDC_PARA_CHATTERING_PERIOD_MAX,
    IDC_PARA_CHATTERING_PERIOD_MIN,
    IDC_PARA_CHATTERING_AMP_MAX,
    IDC_PARA_CHATTERING_AMP_MIN,
    IDC_PARA_CHATTERING_SET_ALIGN_ROI,
    IDC_PARA_CHATTERING_SET_USER_ROI,
	
	IDC_PARA_BUTTON_ELECTRODESHOULDER_EDGE_PARA,
	IDC_PARA_BUTTON_RIGHTVHOME_EDGE_PARA,
	IDC_PARA_LEFT_EDGE_THRESHOLD,
	IDC_PARA_RIGHT_EDGE_THRESHOLD,
	IDC_PARA_FIRST_EDGE_AT_LEFT,
	IDC_PARA_FIRST_EDGE_AT_RIGHT,
	IDC_PARA_ALIGN_IMAGE_USE_INDEX,
	IDC_PARA_PREPROCESSEDGE_FROM_DARK,
	IDC_PARA_ALIGN_USE_INSPECTION,

	IDC_PARA_TEST_ROI,
	IDC_PARA_TEST_EDGEDETECT,
	IDC_PARA_TEST_TILTTEST,
#ifdef _DRAW_DEFECT_
	IDC_PARA_TEST_COLOR_B,
	IDC_PARA_TEST_COLOR_D,
#endif
	IDC_PARA_ISI_WHITEDEFECTTHRESHOLD,
	IDC_PARA_ISI_BLACKDEFECTTHRESHOLD,
	IDC_PARA_ISI_WHITEINSULATETHRESHOLD,
	IDC_PARA_ISI_BLACKINSULATETHRESHOLD,
	IDC_PARA_ISI_GAPINSULATETHRESHOLD,
	IDC_PARA_ISI_ISLANDTHRESHOLD,
	IDC_PARA_ISI_NGTAGTHRESHOLD,
	IDC_PARA_ISI_LEFTNONCOATINGTHRESHOLD,
	IDC_PARA_ISI_RIGHTNONCOATINGTHRESHOLD,
	IDC_PARA_ISI_SCARBTHRESHOLD,
	IDC_PARA_ISI_NGTAGDIVISION,
	IDC_PARA_ISI_TOPCUTTINGINSP,
	IDC_PARA_ISI_BOTCUTTINGINSP,
	IDC_PARA_ISI_INSULATEINSP,
	IDC_PARA_ISI_OVERLAYINSP,
	IDC_PARA_ISI_BOTOVERLAYINSP,
	IDC_PARA_ISI_NONCOATINGINSP,

	IDC_PARA_VHOMEIGNORE_ROIOFFSET,
	IDC_PARA_ELECTRODE_ROIOFFSET,
	IDC_PARA_INSULATEWIDTH_EDGEPARA,
	IDC_PARA_INSULATEWIDTH_ROIOFFSET,
	IDC_PARA_OVERLAYWIDTH_EDGEPARA,
	IDC_PARA_OVERLAYWIDTH_ROIOFFSET,
	IDC_PARA_BOTOVERLAYWIDTH_EDGEPARA,
	IDC_PARA_BOTOVERLAYWIDTH_ROIOFFSET,
	IDC_PARA_INSULATE_ROIOFFSET,
	IDC_PARA_TOP_CUTTINGINSULATE_ROIOFFSET,
	IDC_PARA_BOT_CUTTINGINSULATE_ROIOFFSET,
	IDC_PARA_ISLAND_ROIOFFSET,
	IDC_PARA_NGTAG_ROIOFFSET,
	IDC_PARA_LEFTNONCOATING_ROIOFFSET,
	IDC_PARA_RIGHTNONCOATING_ROIOFFSET,
	IDC_PARA_SCRAB_ROIOFFSET,


	//Tab 얼라인 관련 추가 
	IDC_PARA_USEINTEKTABALIGN,
	IDC_PARA_DETECTTABBOTHSIDE,
	IDC_PARA_TABTHRESHOLDTOPSIDE,
	IDC_PARA_TABTHRESHOLDBOTTOMSIDE,
	IDC_PARA_TABTAPETHRESHOLDTOPSIDE,
	IDC_PARA_TABTAPETHRESHOLDBOTTOMSIDE,
	IDC_PARA_SHADOWTHRESHOLD,
	IDC_PARA_ROLLERENDTHRESHOLD,
	IDC_PARA_TABTOPBOTTOMFORCECORRECTION,
	IDC_PARA_TABRIGHTPOSCORRECTION,
	IDC_PARA_TABEDGESEARCHHEIGHTPIXEL,
	IDC_PARA_EDGEPOINTFILTERVALUE,
	IDC_PARA_ECTTABROI,
	IDC_PARA_FORCECORRECTIONACTIVATED,
	IDC_PARA_TABEDGESELECTIMAGE,
	IDC_PARA_TABEDGERIGHTSKIPPIXEL,
	IDC_PARA_TABEDGECRITERIA,

	IDC_PARA_TABWIDTH,
	IDC_PARA_TABHEIGHT,
	IDC_PARA_TABEDGEINSPRANGE,
	IDC_PARA_TABRIGHTOFFSET,
	IDC_PARA_TABWHITECOUNT,
	IDC_PARA_TABSEARCHPIXEL,
	IDC_PARA_TAB_NGTAG_OFFSET,
	IDC_PARA_TAB_PERPECTLYFOLD,
	IDC_PARA_TAB_NGTAG_TABPRESSED,

	IDC_PARA_VHOME_HEIGHT_IMAGE_LEFT,
	IDC_PARA_VHOME_HEIGHT_IMAGE_RIGHT,

	IDC_PARA_UNCOATING_ELECTRODE_VHOME_OFFSET,
	IDC_PARA_UNCOATING_ELECTRODE_OFFSET,
	IDC_PARA_UNCOATING_LEFT_BOUNDARY_OUTER_OFFSET,
	IDC_PARA_UNCOATING_LEFT_BOUNDARY_INNER_OFFSET,
	IDC_PARA_UNCOATING_RIGHT_BOUNDARY_OUTER_OFFSET,
	IDC_PARA_UNCOATING_RIGHT_BOUNDARY_INNER_OFFSET,
	IDC_PARA_UNCOATING_BOUNDARY_THRESHOLD,
	IDC_PARA_UNCOATING_ELECTRODE_THRESHOLD,
	IDC_PARA_UNCOATING_FOIL_VHOME_WIDTH,
	IDC_PARA_UNCOATING_FOIL_VHOME_HEIGHT,
	IDC_PARA_SCRAB_ROI_TOP,
	IDC_PARA_SCRAB_ROI_BOTTOM,
	IDC_PARA_SCRAB_ROI_LEFT,
	IDC_PARA_SCRAB_ROI_RIGHT,
	IDC_PARA_SCRAB_THRESHOLD,
	IDC_PARA_SCRAB_OFFSET_X,
	IDC_PARA_SCRAB_OFFSET_Y,
	IDC_PARA_SCRAB_ROISIZE_X,
	IDC_PARA_SCRAB_ROISIZE_Y,
	IDC_PARA_UNCOATING_BOUNDARY_SIZE_X_SPEC,
	IDC_PARA_UNCOATING_ELECTRODE_SIZE_X_SPEC,
	IDC_PARA_SCRAB_SIZE_X_SPEC,
	IDC_PARA_UNCOATING_BOUNDARY_SIZE_Y_SPEC,
	IDC_PARA_UNCOATING_ELECTRODE_SIZE_Y_SPEC,
	IDC_PARA_SCRAB_SIZE_Y_SPEC,
	IDC_PARA_UNCOATING_OVERLAY_SIZE_MIN_SPEC,
	IDC_PARA_UNCOATING_OVERLAY_SIZE_MAX_SPEC,
	IDC_PARA_UNCOATING_INSULATION_SIZE_MIN_SPEC,
	IDC_PARA_UNCOATING_INSULATION_SIZE_MAX_SPEC,

	IDC_PARA_USE_OVERLAY_INSPECTION,

	IDC_PARA_USE_OVERLAY_ADJUST,

	IDC_PARA_USE_NEW_OVERLAY_LOGIC,

	IDC_PARA_OVERLAY_THRESHOLD,
	IDC_PARA_OVERLAY_EDGE_CONTINUOUS_COUNT,
	IDC_PARA_OVERLAY_CALC_METHOD,

	IDC_PARA_OVERLAY_HALF_FILTER_LENGTH,
	IDC_PARA_OVERLAY_GAUSS_DEV,

	IDC_PARA_OVERLAY_EDGE_TYPE,
	IDC_PARA_OVERLAY_FIND_FIRST_EDGE,

	IDC_PARA_OVERLAY_EDGE_TH,
	IDC_PARA_OVERLAY_SEARCH_DIRECTION,
	IDC_PARA_OVERLAY_EDGE_SEARCH_AREA_COUNT,

	IDC_PARA_USE_BOTTOM_OVERLAY_INSPECTION,

	IDC_PARA_USE_NEW_BOTTOM_OVERLAY_LOGIC,

	IDC_PARA_BOTTOM_OVERLAY_THRESHOLD,
	IDC_PARA_BOTTOM_OVERLAY_EDGE_CONTINUOUS_COUNT,
	IDC_PARA_BOTTOM_OVERLAY_CALC_METHOD,

	IDC_PARA_BOTTOM_OVERLAY_START_EDGE_THRESHOLD,

	IDC_PARA_USE_BOTTOM_OVERLAY_MORPH_CLOSE,
	IDC_PARA_BOT_OVERLAY_MORPH_KERNEL_X,
	IDC_PARA_BOT_OVERLAY_MORPH_KERNEL_Y,

	IDC_PARA_BOT_OVERLAY_HALF_FILTER_LENGTH,
	IDC_PARA_BOT_OVERLAY_GAUSS_DEV,

	IDC_PARA_BOT_OVERLAY_EDGE_TYPE,
	IDC_PARA_BOT_OVERLAY_FIND_FIRST_EDGE,

	IDC_PARA_BOT_OVERLAY_EDGE_TH,
	IDC_PARA_BOT_OVERLAY_SEARCH_DIRECTION,
	IDC_PARA_BOT_OVERLAY_EDGE_SEARCH_AREA_COUNT,

	IDC_PARA_USE_INSULATION_INSPECTION,

	IDC_PARA_USE_INSULATION_ADJUST,

	IDC_PARA_USE_NEW_INSULATION_LOGIC, 

	IDC_PARA_INSULATION_THRESHOLD,
	IDC_PARA_INSULATION_EDGE_CONTINUOUS_COUNT,
	IDC_PARA_INSULATION_CALC_METHOD,

	IDC_PARA_INSULATION_HALF_FILTER_LENGTH,
	IDC_PARA_INSULATION_GAUSS_DEV,

	IDC_PARA_INSULATION_EDGE_TYPE,
	IDC_PARA_INSULATION_FIND_FIRST_EDGE,

	IDC_PARA_INSULATION_EDGE_TH,
	IDC_PARA_INSULATION_SEARCH_DIRECTION,
	IDC_PARA_INSULATION_SURFACEINSP,

	IDC_PARA_USE_BOTTOM_INSULATION_INSPECTION,

	IDC_PARA_BOT_INSULATION_HALF_FILTER_LENGTH,
	IDC_PARA_BOT_INSULATION_GAUSS_DEV,

	IDC_PARA_BOT_INSULATION_EDGE_TYPE,
	IDC_PARA_BOT_INSULATION_FIND_FIRST_EDGE,

	IDC_PARA_BOT_INSULATION_EDGE_TH,
	IDC_PARA_BOT_INSULATION_SEARCH_DIRECTION,

	IDC_PARA_ROI_OFFSET_INSULATION,
	IDC_PARA_ROI_OFFSET_OVERLAY,
	IDC_PARA_ROI_OFFSET_BOTOVERLAY,
	IDC_PARA_UNCOATING_SURFACE_WHITE_THRESHOLD,
	IDC_PARA_UNCOATING_SURFACE_BLACK_THRESHOLD,

	IDC_UNCOATING_SURFACE_DISPLAY_DETAIL,

	IDC_PARA_UNCOATING_SURFACE_MINIPINHOLE,
	IDC_PARA_UNCOATING_SURFACE_MINIPINHOLE_SIZEX,
	IDC_PARA_UNCOATING_SURFACE_MINIPINHOLE_SIZEY,
	IDC_PARA_UNCOATING_SURFACE_MINIPINHOLE_COUNT,
	IDC_PARA_UNCOATING_SURFACE_MINICRATER,
	IDC_PARA_UNCOATING_SURFACE_MINICRATER_SIZEX,
	IDC_PARA_UNCOATING_SURFACE_MINICRATER_SIZEY,
	IDC_PARA_UNCOATING_SURFACE_MINICRATER_COUNT,

	IDC_PARA_UNCOATING_SURFACE_MINIPROTRUTION,
	IDC_PARA_UNCOATING_SURFACE_MINIPROTRUTION_IFAND,
	IDC_PARA_UNCOATING_SURFACE_MINIPROTRUTION_SIZEX,
	IDC_PARA_UNCOATING_SURFACE_MINIPROTRUTION_SIZEY,
	IDC_PARA_UNCOATING_SURFACE_MINIPROTRUTION_COUNT,

	IDC_PARA_UNCOATING_SURFACE_MINIDENT,
	IDC_PARA_UNCOATING_SURFACE_MINIDENT_IFAND,
	IDC_PARA_UNCOATING_SURFACE_MINIDENT_SIZEX,
	IDC_PARA_UNCOATING_SURFACE_MINIDENT_SIZEY,
	IDC_PARA_UNCOATING_SURFACE_MINIDENT_COUNT,

	IDC_PARA_USE_INSP_BUMPY,
	IDC_PARA_BUMPY_INSP_AREA_OFFSET,
	IDC_PARA_BUMPY_THRESHOLD,
	IDC_PARA_BUMPY_EDGE_THRESHOLD,
	IDC_PARA_BUMPY_COMPARE_CNT,

	IDC_PARA_UNCOATING_BOUNDARY_INSP_OPTION,
	IDC_PARA_UNCOATING_ELECTRODE_INSP_OPTION,
	IDC_PARA_SCRAB_INSP_OPTION,


	IDC_PARA_UNCOATING_IMAGE_USE_INDEX,

	IDC_PARA_UNCOATING_IMAGE_USE_BOUNDARY_INDEX,
	IDC_PARA_UNCOATING_IMAGE_USE_ELECTRODE_INDEX,
	IDC_PARA_UNCOATING_IMAGE_USE_SCRAB_INDEX,
	IDC_PARA_TAPE_USE_DETECT_BRIGHT_TAPE, 
	IDC_PARA_TAPE_USE_DETECT_DARK_TAPE,
	IDC_PARA_TAPE_THRESHOLD_OFFSET_PLUS,
	IDC_PARA_TAPE_THRESHOLD_OFFSET_MINUS,
	IDC_PARA_TAPE_BARCODEMARK,

	IDC_PARA_ELECTRODE_TORN_VHOME_WIDTH,
	IDC_PARA_ELECTRODE_TORN_VHOME_HEIGHT,
	IDC_PARA_ELECTRODE_TORN_OFFSET_NEAR,
	IDC_PARA_ELECTRODE_TORN_OFFSET_FAR,

	IDC_PARA_SHOULDER_LINE_CALC_METHOD,
	IDC_PARA_SHOULDER_LINE_ORIGIN,
	IDC_PARA_SHOULDER_EDGE_THRESHOLD,
	IDC_PARA_SHOULDER_SEARCH_DIRECTION,
	IDC_PARA_TAB_BOUNDARY_IGNORE_SIZE,
	IDC_PARA_SHOULDERLINE_SAMPLING_COUNT,
	IDC_PARA_SHOULDERLINE_LEFT_SEARCH_OFFSET,
	IDC_PARA_SHOULDERLINE_RIGHT_SEARCH_OFFSET,
	IDC_PARA_SHOULDERLINE_RANGE,
	IDC_PARA_CELL_BOUNDARY_ORIGIN,
	IDC_PARA_CALL_BOUNDARY_CALC_POSITION_TOP,
	IDC_PARA_CALL_BOUNDARY_CALC_WIDTH_TOP,
	IDC_PARA_CELL_BOUNDARY_CALC_POSITION_BOTTOM,
	IDC_PARA_CELL_BOUNDARY_CALC_WIDTH_BOTTOM,
	IDC_PARA_CELL_BOUNDARY_SIDE_OPTION,
	IDC_PARA_CELL_BOUNDARY_SAMPLING_COUNT,
	IDC_PARA_SHOULDERLINE_IMAGE_USE_INDEX,
	IDC_PARA_SHOULDERLINE_USE_INSPECTION,
	IDC_PARA_SHOULDER_LINE_HALF_FILTER_LENGTH,
	IDC_PARA_SHOULDER_LINE_GAUSSIAN_DEVIATION,

	IDC_PARA_INSULATION_WHITE_ROI_OFFSET,

	IDC_PARA_INSULATION_DARK_REJECT_INSPECT,
	IDC_PARA_INSULATION_DARK_REJECT_THRESHOLD,
	IDC_PARA_INSULATION_DARK_REJECT_RATIO,

	IDC_PARA_USE_INSULATE_GAP_REJECT_INSPECT,
	IDC_PARA_USE_INSULATE_GAP_REJECT_THRESHOLD,

	IDC_PARA_USE_BOTTOM_CUTTING_HEIGHT_REJECT_INSPECT,
	IDC_PARA_BOTTOM_CUTTING_HEIGHT_REJECT_ROI_OFFSET,
	IDC_PARA_USE_TOP_CUTTING_HEIGHT_REJECT_INSPECT,
	IDC_PARA_TOP_CUTTING_HEIGHT_REJECT_ROI_OFFSET,

	IDC_PARA_TAB_FOLDING_OFFSET_TOP,
	IDC_PARA_TAB_FOLDING_OFFSET_BOTTOM,
	IDC_PARA_TAB_FOLDING_OFFSET_LEFT,
	IDC_PARA_TAB_FOLDING_OFFSET_RIGHT,
	IDC_PARA_TAB_FOLDING_THRESHOLD,
	IDC_PARA_TAB_FOLDING_THRESHOLD2,
	IDC_PARA_USE_SPEC_HEIGHT_FOR_INSPECTION,
	IDC_PARA_USE_TAB_HEAD_INSPECTION,
	IDC_PARA_TAB_HEAD_INSPECTION_METHOD,
	IDC_PARA_TAB_FOLDING_SIZE_SPEC,
	IDC_PARA_TAB_FOLDING_HEIGHT_SPEC,
	IDC_PARA_TAB_FOLDING_WIDTH_SPEC,
	IDC_PARA_NO_TAB_HEIGHT_SPEC,
	IDC_PARA_NO_TAB_WIDTH_SPEC,
	IDC_PARA_TAB_WIDTH_MIN_OFFSET_SPEC,
	IDC_PARA_TAB_WIDTH_MAX_OFFSET_SPEC,
	IDC_PARA_TAB_HEIGHT_MIN_OFFSET_SPEC,
	IDC_PARA_TAB_HEIGHT_MAX_OFFSET_SPEC,
	IDC_PARA_TAB_FOLDING_USE_AND_OR,
	IDC_PARA_TAB_FOLDING_IMAGE_USE_INDEX,
	IDC_PARA_TAB_FOLDING_USE_INSPECTION,
	IDC_TAB_FOLDING_DISPLAY_DETAIL,

	IDC_PARA_NG_THRESHOLD,

	IDC_PARA_BURR_THRESHOLD_TOPLINE_OUTER_RECT,
	IDC_PARA_BURR_THRESHOLD_TOPLINE_OUTER_ELECTRODE_RECT,
	IDC_PARA_BURR_THRESHOLD_TOPLINE_INNER_RECT,
	IDC_PARA_BURR_THRESHOLD_BOTTOMLINE_INNER_RECT,
	IDC_PARA_BURR_THRESHOLD_BOTTOMLINE_OUTER_RECT,
	IDC_PARA_BURR_THRESHOLD_BOTTOMLINE_OUTER_ELECTRODE_RECT,
	IDC_PARA_BURR_THRESHOLD_ROI_RIGHT,
	IDC_PARA_BURR_THRESHOLD_ROI_RIGHT_LOWER,
	IDC_PARA_BURR_THRESHOLD_ROI_LEFT,
	IDC_PARA_BURR_THRESHOLD_ROI_LEFT_ELECTRODE_RECT,
	IDC_PARA_BURR_IMAGE_USE_INDEX,
	IDC_PARA_BURR_SHOW_ROI,
	IDC_PARA_BURR_CHANGE_ROI_X,
	IDC_PARA_BURR_CHANGE_ROI_Y,
	IDC_PARA_BURR_ROI_POS_X,
	IDC_PARA_BURR_ROI_POS_Y,
	IDC_PARA_BURR_SPEC_SIZE,

	IDC_PARA_PITCH_CALC_METHOD,
	IDC_PARA_CELL_LENGTH_TILT_CALC_POSITION,
	IDC_PARA_USE_MISMATCH,
	IDC_PARA_USE_CELL_PITCH,
	IDC_PARA_USE_CELL_LENGTH_TOP,
	IDC_PARA_USE_CELL_LENGTH_BOTTOM,
	IDC_PARA_USE_CELL_LENGTH_2,
	IDC_PARA_USE_TAB_WIDTH,
	IDC_PARA_USE_TAB_HEIGHT,
	IDC_PARA_USE_TAB_HEIGHT_2,
	IDC_PARA_USE_MISALIGN,
	IDC_PARA_USE_V_HOME_TILT_TOP,
	IDC_PARA_USE_V_HOME_TILT_BOT,
	IDC_PARA_USE_TAB_SIDE,
	IDC_PARA_USE_CUTTING_HEIGHT_TOP,
	IDC_PARA_USE_CUTTING_HEIGHT_BOT,
	IDC_PARA_USE_V_HOME_HEIGHT_LEFT,
	IDC_PARA_USE_V_HOME_HEIGHT_RIGHT,
	IDC_PARA_USE_CENTER_ROI_SPLIT,

	IDC_PARA_MEASURE_IMAGE_USE_INDEX,
	IDC_PARA_MEASURE_USE_INSPECTION,

	IDC_PARA_COPY_PARAM,

	IDC_PARA_MEASURE_TOP_CUTTING_HEIGHT_START,
	IDC_PARA_MEASURE_BOT_CUTTING_HEIGHT_START,
	IDC_PARA_MEASURE_TOP_CUTTING_HEIGHT_AREA,
	IDC_PARA_MEASURE_BOT_CUTTING_HEIGHT_AREA,

	IDC_PARA_FIND_CELL_EDIGE_FROM_DARK_PIXEL,
	IDC_PARA_CELL_USE_UNLIMIT_RANGE,
	IDC_PARA_TAB_LEFT_NOISE_VALUE,
	IDC_PARA_USE_TAB_LEFT_FIRST_EDGE,
	IDC_PARA_TAB_MERGE,
	IDC_PARA_TAB_THRESHOLD_TYPE,
	IDC_PARA_TAB_INNER_SIDE_INSPECTION,
	IDC_PARA_SHOULDER_RANSAC_DISTANCE_TH,
	IDC_PARA_SHOULDER_EDGE_SEARCH_DIRECTION,
	IDC_PARA_SHOULDER_USE_FIRST_EDGE,
	IDC_PARA_SHOULDER_COATING_STD_SPEC,
	IDC_PARA_SHOULDER_USE_COATING_INSP,
	IDC_PARA_BURR_USE_INSP,
	IDC_PARA_SAVE_MEASURE_RESULT,
	IDC_PARA_MEASURE_TAB_SIDE_CALC_POS,
	IDC_PARA_MEASURE_DETAIL_CELL_LENGTH_CALC,
	IDC_PARA_MEASURE_USE_FIND_TOP_CUTTING_HEIGHT_FROM_CELL_BOUNDARY,
	IDC_PARA_MEASURE_CUTTING_HEIGHT_TOP_DARK_TH,
	IDC_PARA_MEASURE_CUTTING_HEIGHT_BOT_DARK_TH,
	IDC_PARA_MEASURE_CUTTING_HEIGHT_CONTINUOUS_PIXEL_CNT,
	IDC_PARA_MEASURE_TOP_CUTTING_HEIGHT_DETECTION_START_POINT,
	IDC_PARA_MEASURE_BOT_CUTTING_HEIGHT_DETECTION_START_POINT,
	IDC_PARA_MEASURE_TOP_CUTTING_HEIGHT_DETECTION_AREA,
	IDC_PARA_MEASURE_BOT_CUTTING_HEIGHT_DETECTION_AREA,

	//
	IDC_PARA_SHOW_ROI_MEASURE,
	IDC_PARA_SHOW_ROI_BLOB,
	IDC_PARA_SHOW_ROI_MSA,
	//
	END,
	//DImension Dialog Control List End
};

#define IDC_GRID_DEBUG_INFO						1001
#define IDC_EDIT_BOX							1002


#define ITEM_BOUNDARY_OFFSET1			10
#define ITEM_IMAGENAMESIZE_OFFSET1		55
//#define ITEM_BOUNDARY_OFFSET2			30
#define CAPTION_SIZE_Y					35
#define ITEM_GAP						15


class CXTPPropertyGrid;
class CGridCtrl;
class CSurface_Display;
class CProcessingBase;

#define ShowTestTime(textInfo, elapTime){ if (!elapTime.IsEmpty()) textInfo.SetWindowText(elapTime); }
#define UNIT_MICRO_SECOND			0
#define UNIT_MILLI_SECOND			1
#define UNIT_SECOND					2

#define UPSIDE_CELL_ALIGN			0
#define UPSIDE_UNCOATING			1
#define UPSIDE_SURFACE				2
#define UPSIDE_SCRAB				3
#define UPSIDE_TAB					4
#define UPSIDE_TAPE					5
#define UPSIDE_ELECTRODE_TORN		6
#define UPSIDE_SHOULDER_LINE		7
//#define UPSIDE_TAB_FOLDING			9
#define UPSIDE_NG_MARK				8
#define UPSIDE_MISMATCH				9
#define UPSIDE_BURR					10
#define UPSIDE_ETC					11

#define DOWNSIDE_CELL_ALIGN			12
#define DOWNSIDE_UNCOATING			13
#define DOWNSIDE_SURFACE			14
#define DOWNSIDE_SCRAB				15
#define DOWNSIDE_TAB				16
#define DOWNSIDE_TAPE				17
#define DOWNSIDE_ELECTRODE_TORN		18
#define DOWNSIDE_SHOULDER_LINE		19
//#define DOWNSIDE_TAB_FOLDING		23
#define DOWNSIDE_NG_MARK			20
#define DOWNSIDE_MISMATCH			21
#define DOWNSIDE_BURR				22	
#define DOWNSIDE_ETC				23
#define DOWNSIDE_END				24




typedef struct _TEST_TIMER		// Test �ð� ���� struct
{
	LARGE_INTEGER Frequency;
	LARGE_INTEGER BeginTime;
	LARGE_INTEGER EndTime;

	void StartTimer() { QueryPerformanceCounter(&Frequency); QueryPerformanceCounter(&BeginTime); }
	void EndTimer() { QueryPerformanceCounter(&EndTime); }
	double GetTime() { return (double)(EndTime.QuadPart - BeginTime.QuadPart) / (double)Frequency.QuadPart; }
	void Clear() { memset(this, 0, sizeof(struct _TEST_TIMER)); }

}TEST_TIMER;

// CDlgInspectionMain ��ȭ �����Դϴ�.

class CDlgInspectionMain : public CDialog
{
	DECLARE_DYNAMIC(CDlgInspectionMain)

public:
    CDlgInspectionMain(Inspection::Root* inspection, int nLanguage, Inspection::SetupImage& setupImage, long nType, CWnd* pParent = NULL); // ǥ�� �������Դϴ�.
	virtual ~CDlgInspectionMain();

	bool m_needToRecipeSave;
    long m_nMachineType;

private:
	Database m_dbEdit_Common;
	Database m_dbEdit_Module;

	static void CallbackOnROIChanged(const long id, void *userData, const wchar_t * szKey);
	static void CallbackOnMeasurementChanged(const long id, void *userData, const IPVM::LineSeg_32f &line);
	static void CallbackOnMeasurementEnd(const long id, void *userData, const IPVM::LineSeg_32f &line);
#ifdef _DRAW_DEFECT_
	static void callbackMouseClickedDown(const long id, void* userData, const IPVM::Point_32f_C2& pt);
	void callbackMouseClickedDown(const long id, const IPVM::Point_32f_C2& pt);
	static void callbackMouseMoved(const long id, void* userData, const IPVM::Point_32f_C2& pt);
	void callbackMouseMoved(const long id, const IPVM::Point_32f_C2& pt);
	static void callbackMouseClickedUp(const long id, void* userData, const IPVM::Point_32f_C2& pt);
	void callbackMouseClickedUp(const long id, const IPVM::Point_32f_C2& pt);
	void DrawDefect(const IPVM::Point_32f_C2& pt);
	bool bDraw;
	void OnBnClickedColor(const LPARAM& lparam);

	BOOL m_isUseDrawDefect;
	COLORREF m_BrightColor;
	COLORREF m_DarkColor;
	long m_Size;
	long m_Type;
#endif
	bool bisBrightImage;
	void CallbackOnROIChanged(const wchar_t * szKey);
	void CallbackOnMeasurementChanged(const IPVM::LineSeg_32f &line);
	void CallbackOnMeasurementEnd();
	bool ParameterAppliedWhenQuit();
	bool ParameterApplied();
	afx_msg LRESULT ShowProfileView(WPARAM wParam, LPARAM lParam);
public:
	void InitInspecitonItemGrid();
	void InitInspecitonDebugInfo();
	void InitInspecitonButton(CRect viewRect);

	void ChangeEditInspectionItem(bool isUp, ProcItemCategory categoryIndex);
	void UpdateEditInspectionItem(long nSide  = 1, bool bUpdate = true);
	void UpdateInspectionParaGrid();

	void OnBnClickedButtonCellDesign();

	void OnBnClickedButtonUpsideTabConfiguration();
	void OnBnClickedButtonUpsideTabCellAlign();
	void OnBnClickedButtonUpsideTabUncoating();
	void OnBnClickedButtonUpsideSurface();
	void OnBnClickedButtonUpsideSpec();
	void OnBnClickedButtonUpsideScrab();
	void OnBnClickedButtonUpsideTab();
	void OnBnClickedButtonUpsideTabShoulderLine();
	void OnBnClickedButtonUpsideTabTape();
	void OnBnClickedButtonUpsideTabFolding();
	void OnBnClickedButtonUpsideTabElectrodeTorn();
	void OnBnClickedButtonUpsideNgMark();
	void OnBnClickedButtonUpsideMeasure();
    void OnBnClickedButtonUpsideChattering();
	void OnBnClickedButtonUpsideBurr();
	void OnBnClickedButtonUpsideEtc();
	void OnBnClickedButtonUpsideISI();
	void OnBnClickedButtonUpsideBlob();
	void OnBnClickedButtonUpsideDeeplearning();
	void OnBnClickedButtonUpsideAbnormalInspection();

	void OnBnClickedButtonDownsideTabConfiguration();
	void OnBnClickedButtonDownsideTabCellAlign();
	void OnBnClickedButtonDownsideTabUncoating();
	void OnBnClickedButtonDownsideSurface();
	void OnBnClickedButtonDownsideSpec();
	void OnBnClickedButtonDownsideScrab();
	void OnBnClickedButtonDownsideTab();
	void OnBnClickedButtonDownsideTabShoulderLine();
	void OnBnClickedButtonDownsideTabTape();
	void OnBnClickedButtonDownsideTabFolding();
	void OnBnClickedButtonDownsideTabElectrodeTorn();
	void OnBnClickedButtonDownsideNgMark();
	void OnBnClickedButtonDownsideMeasure();
    void OnBnClickedButtonDownsideChattering();
	void OnBnClickedButtonDownsideBurr();
	void OnBnClickedButtonDownsideEtc();
	void OnBnClickedButtonDownsideISI();
	void OnBnClickedButtonDownsideBlob();
	void OnBnClickedButtonDownsideDeeplearning();
	void OnBnClickedButtonDownsideAbnormalInspection();

	void OnBnClickedUseEdgeDetect();
	void OnBnClickedUseVhomeTiltTest();
	
	void OnBnClickedButtonCellDesignShowOverlay();
	void DrawCellDesign(long nXAxisOffset, long nYAxisOffset,
		IPVM::Point_32f_C2& ptLeftTopVhome = IPVM::Point_32f_C2(0, 0),
		IPVM::Point_32f_C2& ptLeftBotVhome = IPVM::Point_32f_C2(0, 0),
		IPVM::Point_32f_C2& ptRightTopVhome = IPVM::Point_32f_C2(0, 0),
		IPVM::Point_32f_C2& ptRightBotVhome = IPVM::Point_32f_C2(0, 0),
		long nTabOffsetX = 0, long nTabOffsetY = 0);
	void MoveROItoPoint(IPVM::Rect& rtRoi, const IPVM::Point_32f_C2& pt);
	void OnBnClickedButtonRuluer();

	void OnBnClickedButtonParaCellAlignVhomeROI(const int& nID);
	void OnChangedCellAlignImageUseIndex();
    void OnBnClickedSwapMinAreaBoxXY();
	void OnBnClickSelectInspType(const int& nID);
	void OnBnClickedButtonCopyROI(const int& nID);
	void OnBnClickedButtonMSAAlign(const int& nID);
    void OnBnClickedButtonAutoFindEdgeDetectROI(const int& nID);
    void AutoFindEdgeDetectROI2();

	void OnSelectImageType(LPARAM lparam, const int& nID);
    void OnChangedCellImageMirror(const int& nID);

	void ShowBotOverlayInspArea();

	void OnBnClickedShowEdgeDetectParas(LPARAM lparam, const int& nID);
	void OnBnClickedAddDetailInspSetting(LPARAM lparam, const int& nID);
	void OnBnClickedDeleteDetailInspSetting(LPARAM lparam, const int& nID);
	
	void OnChangedTabFoldingThreshold();

	void UpdateCheckBoxChilds(const LPARAM& lparam);

	void OnChangedBlobUseInspection(LPARAM lparam, int nID);
	void OnChangedBlobThreshold(LPARAM lparam, int nID);
	void OnChangedBlobThreshold2(LPARAM lparam, int nID);
	void OnChangedBlobRoi(LPARAM lparam, int nID);
	void OnChangedBlobRoiDiv(LPARAM lparam, int nID);
	void OnChangedBlobEqualUse(LPARAM lparam, int nID);
	void GetParaNgMark(UINT id);

	void OnChangedAbnormalRoi(LPARAM lparam, int nID);
	void OnChangedAbnormalGV(LPARAM lparam, int nID);
	void OnChangedAbnormalUseInspection(LPARAM lparam, int nID);

	void OnChangedChatteringlRoi(int nID);

	void OnBnClickedButtonParaMeasureImageUseIndex();

	CXTPPropertyGridItem* PropertyAdd_AndOr(CXTPPropertyGridItem* parent, LanguageDef def, bool& value);

	void UpdateInspectionParaGridCellDesign();
	void UpdateInspectionParaGridCellAlign();
	void UpdateInspectionParaGridDeeplearning();
	void UpdateInspectionParaGridAbnormalInspection();
    void UpdateInspectionParaGridChattering();


	void UpdateInspectionParaGridSurface();

	void UpdateInspectionParaGridSpec();

	void UpdateInspectionParaGridMeasure();

	void UpdateInspectionParaGridBlob();

	bool IsCurrentParaChanged();
	bool IsSameModule(bool isUp, ProcItemCategory categoryIndex);

	void UpdateInspectionDebugInfo();
	void UpdateInspectionDebugInfoColor();

	void UpdateInspectionTextInfoTestTime(float elapTime, int timeUnit, bool bTimeout = false);


	void UpdateInspectionItemGrid();
	int GetCurrentInspectionItemID();
	int GetCurrentInspectionItemType();

	void ShowRejectROI();
	void ShowRejectROI_Event();
	void ShowAllRejectROI();
	bool CheckSurfaceDefect(CString Detail);

	void SaveMeasureResult();

	BOOL ManualTestAll(bool bUpdate = TRUE);

	void ShowROI(bool isup, ProcItemCategory& ItemCategory);
	bool SetExplain(CXTPPropertyGridItem* item, long nID);
	void OnClickedUseIntekTabAlign();

	//BOOL SaveROIImage(IPVM::Image_8u_C1 image, IPVM::Rect rtROI, IPVM::Rect rtArea, int nNum);

public:
	bool bcheckbox;
	BOOL m_isUseEdgeDetect;
	long m_FilterLength;
	float m_Gaus;
	int m_ShowProfile;
	BOOL m_FindFirst;
	int m_DetectType;
	int m_Direction;
	float m_EdgeTh;
	BOOL m_isUseEdgeDetects;
	long m_nSearchWidth;
	long m_nFindEdge;

	BOOL m_isUseVhomeTiltTest;
   
	IPVM::Image_8u_C1*					    m_ResultABSImage;
    IPVM::Image_8u_C1*						m_ResultGammaImage;

	IPVM::Image_8u_C1*						m_curSelImage;

	std::vector<IPVM::EdgeDetectionDebugInfo>			m_vecEdgeInfo;
	//CSurface_Display* m_DlgSurfaceDisplay;
	CXTPPropertyGrid*						m_inspectionItemGrid;
	CXTPPropertyGrid*						m_inspectionParaGrid;
	CEdit									m_editTextInformation;
	IPVM::ProfileView*						m_profileView;
	Inspection::ImageViewEx*				m_imageView;
	long									m_inspectionGridSizeX;
	CGridCtrl*								m_debugInfoGrid;
	Inspection::SetupImage					m_setupImage;
	IPVM::Image_8u_C1						m_inspectionImageBright;
	IPVM::Image_8u_C1						m_inspectionImageDark;
	std::vector <IPVM::Image_8u_C1>			m_vecMultiCellImage;
	int										m_nMultiImageIndex;
	Inspection::Root*						m_inspectionRoot;
	bool									m_curIsUp;
	ProcItemCategory						m_curItemCategory;
	bool									m_oldIsUp;
	ProcItemCategory						m_oldItemCategory;
	int										m_nLanguage;
	bool									m_ExcelOpen;

	TEST_TIMER								m_TestTimer;
	CString									m_TestTime[DOWNSIDE_END];

	BOOL									m_isFirstRun;

	Inspection::DebugInfo					m_debugInfo;

	Share::enLoginMode m_loginMode;

	bool		m_btest;

	std::map <long, std::vector<CString>>				m_mapExplainParam;

	// Language
	//Common
	CString strLeft;
	CString strRight;
	CString strUse;
	CString strNotUse;
	CString strUseInspection;
	CString strImageBrightBackImage;
	CString strImageDarkBackImage;
	CString strImageUseIndex;

	CString strOption;


	CString strImageBoundaryBrightBackImage;
	CString strImageBoundaryDarkBackImage;
	CString strImageUseBoundaryIndex;

	CString strImageElectrodeBrightBackImage;
	CString strImageElectrodeDarkBackImage;
	CString strImageUseElectrodeIndex;

	CString strImageScrabBrightBackImage;
	CString strImageScrabDarkBackImage;
	CString strImageUseScrabIndex;


	CString strOffset;
	CString strThreshold;
	CString strSpec;
	CString strPreprocess;
	CString strLengthSpec;
	CString strLengthSpecMM;
	CString strMeasureOffset;
	CString strAnd;
	CString strOr;
	CString TabFolding;

	// Configuration
	CString strMarkThresholdValue;
	CString strMarkThickness;
	CString strMarkScanLeft;
	CString strMarkScanRight;
	CString strMarkEdgeDirection;

	CString strAutoManual;
	//EdgeDetectFilter
	CString strHalfFilterLength;
	CString strGaussianDeviation;

	//EdgeDetectPara
	CString strUseFirstEdge;
	CString strEdgeTheshold;
	CString strDirection;
	CString strDetectType;

	//Inline
	CString strInlineLeft;
	CString strInlineRight;
	CString strInlineTabThreshold;
	CString strBackgroundLeft;
	CString strBackgroundRight;
	CString strVhomeExistance;
	
	CString strVhomeMakeUpper_USING_IMAGE;
	CString strVhomeMakeUpper_LEFT;
	CString strVhomeMakeUpper_RIGHT;

	CString strVhomeMakeUpper_LEFT_VALUE;
	CString strVhomeMakeUpper_RIGHT_VALUE;
	CString strVhomeMakeUpper_MoveROI;
	CString strVhomeMakeUpper_CompareXPos;

	CString strUseVhomeSpecDistance;
	CString strVhomeMoveTogether;
	CString strVhomeBlobMerge;
	CString strVhomeBlobMergeDistance;
	CString strWhiteAuto;
	CString strBlackAuto;
	CString strWhiteManualSimple;
	CString strBlackManualSimple;
	CString strWhiteEdgeDetect;
	CString strBlackEdgeDetect;
	CString strTest;
	CString strWhite;
	CString strBlack;

	//Cell
	CString strTabDirection;
	CString strBoundarySearchSize;
	CString strBoundarySearchSizeUPDOWN;
	CString strShowVHomeROI;
    CString strSplitCenterROI;
	CString strTabExistance;
	CString strTabThreshold;
	CString strTabMerge;
	CString strSearchTabLeftFromVHome;
	CString strTabBoundaryIgnore;
	CString strCellBoundaryPosition;
	CString strGage;
	CString strManualTabROI;
	CString strRollerROI;
	CString strTabInnerDetailSearchOffset;
	CString strTabOuterDetailSearchOffset;
	CString strTabBoundaryFirstEdge;
	CString strTabBoundaryEdgeThreshold;
	CString strRollerBoundaryLineForTab;
	CString strVHomeLeftTop;
	CString strVHomeLeftBot;
	CString strVHomeRightTop;
	CString strVHomeRightBot;

	//Tab 얼라인 관련 추가 
	CString strUseIntekTabAlign;
	CString strDetectTabBothSide;
	CString strTabThresholdTopSide;
	CString strTabThresholdBottomSide;
	CString strTabTapeThresholdTopSide;
	CString strTabTapeThresholdBottomSide;
	CString strShadowThreshold;
	CString strRollerEndThreshold;
	CString strTabTopBottomForceCorrection;
	CString strTabRightPosCorrection;
	CString strTabEdgeSearchHeightPixel;
	CString strEdgePointFilterValue;
	CString strectTabROI;
	CString strForceCorrectionActivated;
	CString strTabEdgeSelectImage;
	CString strTabEdgeRightSkipPixel;
	CString strTabEdgeCriteria;
	CString strTabWidth;
	CString strTabHeight;
	CString strTabEdgeInspRange;
	CString strTabRightOffset;
	CString strTabWhiteCount;
	CString strTabSearchPixel;

	//Uncoating
	CString strUncoating;
	CString strBoundaryOffset;
	CString strLeftBoundaryOuterOffset;
	CString strLeftBoundaryInnerOffset;
	CString strRightBoundaryOuterOffset;
	CString strRightBoundaryInnerOffset;
	CString strBoundaryThreshold;
	CString strElectrodeThreshold;
	CString strVHomeIgnore;
	CString strVHomeWidth;
	CString strVHomeHeight;
	CString strGeneral;
	CString strScrab;
	CString strScrabROI;
	CString strBoundarySizeSpecX;
	CString strElectrodeSizeSpecX;
	CString strScrabSizeSpecX;

	CString strBoundarySizeSpecY;
	CString strElectrodeSizeSpecY;
	CString strScrabSizeSpecY;

	CString strOverlaySizeSpecMin;
	CString strOverlaySizeSpecMax;
	CString strInsulationSizeSpecMin;
	CString strInsulationSizeSpecMax;

	CString strBoundaryInspOption;
	CString strElectrodeInspOption;
	CString strScrabInspOption;

	CString strUseBoundaryInspection;
	CString strUseElectrodeInspection;
	CString strUseScrabInspection;
	CString strUseSkipScrabInspAfterTape;
	CString strUseOverlayInspection;
	CString strUseInsulationInspection;
	CString strUseSurfaceInspection;
	CString strUseTabInspection;
	CString strUseSpurInspection;

	
	//Tape
	CString strThresholdPlusOffset;
	CString strThresholdMinusOffset;
	CString strTapeReference1;
	CString strTapeReference2;
	CString strWhiteSpec;
	CString strBlackSpec;
	CString strReductionRate;

	//EletrodeTorn
	CString strElectrodeTorn;
	CString strVHomeWidthSize;
	CString strVHomeHeightSize;
	CString strNearOffset;
	CString strFarOffset;
	CString strDarkThresholdRatio;
	CString strBrightThresholdOffset;

	//Tab
	CString strOffsetTop;
	CString strOffsetBottom;
	CString strOffsetRight;
	CString strTopThreshold;
	CString strBottomThreshold;
	CString strInspectionIgnoreInnerOffset;
	CString strCapIgnoreOffset;
	CString strThresholdType;
	CString strUseSpecHeightForInspection;
	CString strUseRightInspection;
	CString strTabHeadInspectionMethod;
	CString strTabHeadInspectionEdge;
	CString strTabHeadInspectionBlob;
	CString strHeightError;
	CString strWidthError;
	CString strNoTabHeightError;
	CString strNoTabWidthError;
	CString strTabWidthMinSpec;
	CString strTabWidthMaxSpec;
	CString strTabHeightMinSpec;
	CString strTabHeightMaxSpec;
	CString strUseAndOr;
	CString strAreaMin;
	CString strHeightOffset;
	CString strThresholdOffset;
	CString strEdgeThreshold;

	//burr
	CString strBurrThreshold_TopOuter;
	CString strBurrThreshold_TopOuter_Electrode;
	CString strBurrThreshold_TopInner;
	CString strBurrThreshold_BottomInner;
	CString strBurrThreshold_BottomOuter;
	CString strBurrThreshold_BottomOuter_Electrode;
	CString strBurrThreshold_RoiRight;
	CString strBurrThreshold_RoiRight_Lower;
	CString strBurrThreshold_RoiLeft;
	CString strBurrThreshold_RoiLeft_Electrode;
	CString strOffsetX;
	CString strOffsetY;
	CString strRoiSizeX;
	CString strRoiSizeY;
	CString strBurrROIPosX;
	CString strBurrROIPosY;
	CString strBurrSpecSizeX;
	CString strBurrSpecSizeY;
	CString strBurrLeft;
	CString strBurrTopOuter;
	CString strBurrBottomOuter;
	CString strBurrRight;

	//CString strBurrBottomInner;

	//NGMark
	CString strFind;
	CString strNGMarkFindOffsetLeft;
	CString strNGMarkFindOffsetRight;
	CString strNGMarkFindOffsetY;
	CString strNGMark1;
	CString strNGMark2;
	CString strNGMark3;
	CString strEnable;
	CString strDisable;
	CString strNGMarkSizeX;
	CString strNGMarkSizeY;
	CString strNGMarkPitch;
	CString strNGMarkCount;
	CString strNGMarkMaxAverageIntensity;
	CString strNGMarkYaxisMergeCount;
	CString strNGMarkFrequencyFilter;
	CString strNGMarkMinBlackPercent;
	CString NGMarkFindCount;
	CString NGMarkOption;
	CString SubMark;

	//Area 
	std::vector<Inspection::SetupImage> m_vecsetupImage_Area;
	// ��ȭ ���� �������Դϴ�.
	enum { IDD = IDD_DIALOG_MAIN };

protected:
	virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV �����Դϴ�.
	CStatic m_captionInspectionItem;
	CStatic m_captionInspectionPara;
	CStatic m_captionDebugInfo;
	CStatic m_captionSetting;
	CButton m_buttonSettingUndo;
	CStatic m_boxSetting;
	CStatic m_captionImage;
	CButton m_buttonImageLoad;
	CStatic m_boxImage;
	CStatic m_captionTest;
	CStatic m_boxTest;
	CButton m_buttonTest;

	DECLARE_MESSAGE_MAP()
public:
	virtual void OnOK();
	virtual void OnCancel();

	virtual BOOL OnInitDialog();
	afx_msg LRESULT OnGridNotify(WPARAM wparam, LPARAM lparam);
	afx_msg void OnBnClickedButtonImageLoad();
	afx_msg void OnBnClickedButtonSettingUndo();
	afx_msg void OnBnClickedButtonTest();
	afx_msg void OnBnClickedButtonShowBrightImage();
	afx_msg void OnBnClickedButtonShowDarkImage();

	afx_msg void OnSelChangedGridDebugInfo(NMHDR* pNMHDR, LRESULT* pResult);
	CStatic m_captionTextInfo;
	afx_msg void OnDestroy();
	afx_msg void OnBnClickedButtonCopyParamsSameItem();
	afx_msg void OnBnClickedButtonAccumulatedImages();
	afx_msg void OnBnClickedButtonTestAll();
	CButton m_buttonTestAll;
	CButton m_buttonShowBrightImage;
	CButton m_buttonShowDarkImage;
	afx_msg void OnBnClickedCheckCopySameUpdown();
	afx_msg void OnBnClickedCheckCopySameTab();
	afx_msg void OnBnClickedCheckCopySamePolar();
	afx_msg void OnBnClickedButtonCellImageMultiSelect();
	CButton m_buttonMultiCellImage;
	CRect rtDisplay;
	void AllLamiObjectNotUse();
    afx_msg LRESULT OnUwmUpdateEditInspectionItem(WPARAM wParam, LPARAM lParam);
 protected:
	bool m_bParamForceSave;
	afx_msg LRESULT OnUserMessageBoxYes(WPARAM wParam, LPARAM lParam);
public:
	afx_msg void OnTimer(UINT_PTR nIDEvent);
	afx_msg void OnBnClickedButtonShowok();
	afx_msg void OnBnClickedButtonShowng();
	afx_msg void OnBnClickedButtonShowskip();
	bool m_bShow_OK;
	bool m_bShow_NG;
	bool m_bShow_SKIP;
	void ShowISIOption(bool bShow);
	bool JobFileSave();
	bool m_bAbnormal;

	CString m_strImageName;
	
	// 장지수 Excel 파일 저장 Main Inspection 으로 위치 변경
    CString m_strImageFileName;
    void ExcelFileSave(CString strSavePath = _T(""));
    void ExcelRejectInput();
    void ExcelRejectDataInput();
    long m_nExcelRow;
    void CreateDir(CString strFolderPath);
	CExcelWrapClass m_ExcelSave;

	void ShowBatchInspRejectROI();
	
	// 해당 함수 필요한 부분은 헤더 쪽에 추가 되어있는 형태라 추가
    CString InspectionArea2String(enInspectionArea type)
    {
        switch (type)
        {
            case enInspectionArea::IA_NONE:
                return _T("None");
                break;
            case enInspectionArea::IA_BACKGROUND_BURR:
                return _T("Burr");
                break;
            case enInspectionArea::IA_SCRAB:
                return _T("Scrab");
                break;
            case enInspectionArea::IA_TAB:
                return _T("Tab");
                break;
            case enInspectionArea::IA_TAB_INSULATION:
            case enInspectionArea::IA_CUTTINGHEIGHT_TOP:
            case enInspectionArea::IA_CUTTINGHEIGHT_BOT:
                return _T("Insulation");
                break;
            case enInspectionArea::IA_ELECTRODE_EDGE:
            case enInspectionArea::IA_ELECTRODE_EDGE_LEFT:
            case enInspectionArea::IA_ELECTRODE_EDGE_RIGHT:
                return _T("Electrode Edge");
                break;
            case enInspectionArea::IA_ELECTRODE:
                return _T("Electrode");
                break;
            default:
                return _T("error");
                break;
        } 
	}

	CDlgBatchInpection* m_dlgBatch;
    BOOL m_bReject; // TestAll 이 끝난후 Reject Data 의 유무 확인
	II_RESULT_VALUE m_nRejectType;
    virtual BOOL PreTranslateMessage(MSG* pMsg);
};

