#pragma once

#define TIMER_ID_CLOCK						1
#define TIMER_ID_UPDATE_RESULT_UI			2
#define TIMER_ID_UPDATE_GRAB_QUEUE_STATUS	999


#define TIMER_ID_UPDATE_CPUMEMORY_STATUS	300
#define TIMER_ID_CAMERA_CONNECT_CHECK       301